#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*              Anil Madhavapeddy, OCaml Labs                             *
#*                                                                        *
#*   Copyright 2014 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

sudo: false
language: c
git:
  submodules: false
script: bash -ex tools/ci/travis/travis-ci.sh
matrix:
  include:
  - env: CI_KIND=build XARCH=i386
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6:i386
        - cpp-6:i386
        - binutils:i386
        - binutils-dev:i386
        - libx11-dev:i386
        - libc6-dev:i386
  - env: CI_KIND=build XARCH=x64
  - env: CI_KIND=build XARCH=x64 CONFIG_ARG=-flambda OCAMLRUNPARAM=b,v=0
  - env: CI_KIND=changes
  - env: CI_KIND=tests
  allow_failures:
  - env: CI_KIND=tests
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - binutils-dev
    - gcc-6
    - cpp-6
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60

notifications:
  email:
    - dmitry.bely@gmail.com
